// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZK3RI3FIPQnjqLbEEFQVC3-n0Tm1hZ6A',
    appId: '1:838122088105:web:ff693de139e477db43abb8',
    messagingSenderId: '838122088105',
    projectId: 'my-social-apps-3bef8',
    authDomain: 'my-social-apps-3bef8.firebaseapp.com',
    storageBucket: 'my-social-apps-3bef8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdd5WLQhezgKvQCFga5SrINdqDiXypWOQ',
    appId: '1:838122088105:android:e01024d7cb49b8ae43abb8',
    messagingSenderId: '838122088105',
    projectId: 'my-social-apps-3bef8',
    storageBucket: 'my-social-apps-3bef8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDElDaj8jj5HsoBQVCKu2eqZ0ptOWa88SM',
    appId: '1:838122088105:ios:c16d2836ecc851c643abb8',
    messagingSenderId: '838122088105',
    projectId: 'my-social-apps-3bef8',
    storageBucket: 'my-social-apps-3bef8.appspot.com',
    iosClientId: '838122088105-lct47t6edmmh3m3c4uf65se843g9bfsc.apps.googleusercontent.com',
    iosBundleId: 'com.floom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDElDaj8jj5HsoBQVCKu2eqZ0ptOWa88SM',
    appId: '1:838122088105:ios:c16d2836ecc851c643abb8',
    messagingSenderId: '838122088105',
    projectId: 'my-social-apps-3bef8',
    storageBucket: 'my-social-apps-3bef8.appspot.com',
    iosClientId: '838122088105-lct47t6edmmh3m3c4uf65se843g9bfsc.apps.googleusercontent.com',
    iosBundleId: 'com.floom',
  );
}
